spring:
  application:
    name: apollo-adminservice
  profiles:
    active: github
  cloud:
    inetutils:
      ignored-interfaces:
       - docker0
       - veth.*
ctrip:
  appid: 100003172
  
server:
  port: 10020
  
#logging:
#  path: /opt/logs/100003172
#  file: ${logging.path}/apollo-adminservice.log
