spring:
  application:
    name: apollo-adminservice
  profiles:
    active: github

ctrip:
  appid: 100003172
  
server:
  port: 10020
  
#logging:
#  path: /opt/logs/100003172
#  file: ${logging.path}/apollo-adminservice.log
