spring:
  application:
    name: apollo-configservice
  profiles:
    active: github

ctrip:
  appid: 100003171
  
server:
  port: 10010
  
#logging:
#  path: /opt/logs/100003171
#  file: ${logging.path}/apollo-configservice.log
